using MathGame.AbstractBases;
using MathGame.CoreUtilities;
using MathGame.GameQuestion;

namespace MathGame.GameWindows;

public class HistoryWindow : WindowBase
{
    private int _currentPage;
    private int _rowsPerPage;

    private int TotalPages
    {
        get
        {
            int actualTotalRecords = GameEngine.GameHistoryTable.Count;
            return Math.Max(1, (actualTotalRecords + _rowsPerPage - 1) / _rowsPerPage);
        }
    }

    public override string ValidOptions => "";
    public override int CurrentErrorLocation => 100;

    public HistoryWindow()
    {
        _currentPage = 1;
        _rowsPerPage = 15;
    }

    public override void Render()
    {
        // setting up the input handler
        InputHandler.CurrentErrorLocation = 2;
        InputHandler.SetActiveOptions = "np";

        // calculating the total number of element to skip
        int skipAmount = (_currentPage - 1) * _rowsPerPage;

        // getting via link the total pages to use
        var rowsToDisplay = GameEngine.GameHistoryTable
            .OrderByDescending(r => r.Id) // Get the latest games first
            .Skip(skipAmount)
            .Take(_rowsPerPage)
            .ToList();
        // serring the space to offset before printing the table

        int offset = 11;
        // this is generated by AI not me to save some time
        string rowFormat = "| {0,-4} | {1,-10} | {2,-7} | {3,-10} | {4,-8} | {5,-10} | {6,-10} |";
        Console.SetCursorPosition(0, offset);
        Console.Write(string.Format(
            rowFormat, "Id", "start Date", " Score", "Difficulty", "Op", "Q Type",
            "Total Qs"
        ));
        Console.Write("\r\n");
        Console.Write("|------|------------|---------|------------|----------|------------|------------|");
        Console.Write("\r\n");
        offset += 1;
        foreach (var record in rowsToDisplay)
        {
            
            offset++;
            Console.SetCursorPosition(0, offset);
            Console.Write(rowFormat,
                record.Id,
                record.PlayedDate.ToString("yyyy-MM-dd"),
                record.TotalScore,
                record.Difficulty,
                record.Operation switch
                {
                    GameOperation.Random => "Random",
                    GameOperation.Subtraction => "-",
                    GameOperation.Multiplication => "x",
                    GameOperation.Division => "÷",
                    GameOperation.Addition => "+",
                    _ => ""
                },
                record.QuestionType,
                record.TotalNumberOfQuestions);
            Console.Write("\r\n");
        }

        Console.SetCursorPosition(0, 0);
        Console.WriteLine($"Page {_currentPage} of {TotalPages}");
        string[] tip =
        [
            "type [n] to move to the next page",
            "type [p] to move back to the previos page",
            "type [q] to return back to the main menu"
        ];
        InputHandler.InputPrompt(tip);
    }

    public override WindowMap ProcessInput(string userInput)
    {
        switch (userInput)
        {
            case "n":
                if (_currentPage < TotalPages)
                {
                    _currentPage++;
                }

                WindowManager.CurrentWindow = WindowMap.HistoryWindow;
                break;

            case "p":
                if (_currentPage > 1)
                {
                    _currentPage--;
                }

                WindowManager.CurrentWindow = WindowMap.HistoryWindow;
                break;

            case "q":
                WindowManager.CurrentWindow = WindowMap.MainMenu;
                break;
            default:
                break;
        }

        return WindowManager.CurrentWindow;
    }
}